config:
  # unencrypted
  TMDB_API_KEY: "7d64f5b814cad7fc6982afb1174e6357"
  TMDB_READ_ACCESS_TOKEN: "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3ZDY0ZjViODE0Y2FkN2ZjNjk4MmFmYjExNzRlNjM1NyIsInN1YiI6IjY1YTMyZTU3Mjk3MzM4MDEyNDEzMTE0NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.X8NUK3AVr_jA2dslYlom23G3C-xeGegl0wcr_NZ1-ok"
  TMDB_URL_BASE: "https://api.themoviedb.org/3"
  database_name: "melli_v5"