from pydantic import BaseModel, Field

class SearchRequest(BaseModel):
    search_term: str

from enum import Enum

class MEDIA_TYPE(Enum):
    SHOW = "SHOW"
    MOVIE = "MOVIE"

class PostReviewRequest(BaseModel):
    media_type: MEDIA_TYPE
    user_id: str
    item_id: str # Matches to TMDB id field
    stars: int = Field(..., ge=0, le=5) # stars is an int with 0 => stars => 5
    timestamp: int # UTC timestamp generated by frontend
    notes: str # User added notes, word limit TBD


class UserReviewsRequest(BaseModel):
    user_id: str


class FeedRequest(BaseModel):
    user_id: str

class ItemReviewsRequest(BaseModel):
    item_id: str

class ItemGetRequest(BaseModel):
    item_id: str